name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:

  dockercitest:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Run pytest container
        run: docker compose up pytest